services:
  # ttyd-frontend:

  pypm:
    container_name: pypm
    build: bastion/ttyd
    ports:
      - 8889:80
    volumes:
      - run-ttyd:/run/ttyd

  nginx:
    build: bastion
    depends_on:
      - pypm
    network_mode: container:pypm
    environment:
      API_GATEWAY_AUTH_URL: https://postman-echo.com/response-headers?X-Cognito-Identity-Id=mock-cognito-identity-id
    entrypoint:
      - /bin/entrypoint.sh
    command:
      - /usr/local/openresty/bin/openresty
    volumes:
      - run-ttyd:/run/ttyd
      - ./bastion/entrypoint.sh:/bin/entrypoint.sh
      - ./bastion/conf:/etc/nginx/conf.d
      - ./bastion/lua:/etc/nginx/lua

volumes:
  run-ttyd:
