# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/pod.json

apiVersion: v1
kind: Pod
metadata:
  name: ttyd-nginx
spec:
  containers:
    - name: pypm
      image: localhost/pypm
      volumeMounts:
        - name: run-ttyd
          mountPath: /run/ttyd

    - name: nginx
      image: openresty/openresty:alpine
      ports:
        - containerPort: 80
          hostPort: 8888
      volumeMounts:
        - name: src
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
        - name: src
          mountPath: /lua
          subPath: lua
        - name: run-ttyd
          mountPath: /run/ttyd

  volumes:
    - name: src
      hostPath:
        path: /home/hwanghyun3/toolchain-cdk/ttyd
    - name: run-ttyd
      emptyDir: {}
