apiVersion: v1
kind: Pod
metadata:
  name: webhook
spec:
  containers:
  - name: stress-webhook
    image: stress-webhook
    ports:
    - containerPort: 9000
    - hostPort: 9000 
  - name: whoami
    image: traefik/whoami
