# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/pod.json

apiVersion: v1
kind: Pod
metadata:
  name: ttyd-nginx
spec:
  containers:
    - name: pypm
      image: localhost/pypm
      volumeMounts:
        - name: run-ttyd
          mountPath: /run/ttyd

    - name: nginx
      image: openresty/openresty:alpine
      command:
        - sh
        - -c
        - >
          addgroup -g 101 -S nginx;
          adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx;
          exec /usr/local/openresty/bin/openresty -g "user nginx; daemon off;"
      ports:
        - containerPort: 80
          hostPort: 8888
      volumeMounts:
        - name: src
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        - name: src
          mountPath: /lua
          subPath: lua
        - name: run-ttyd
          mountPath: /run/ttyd

  volumes:
    - name: src
      hostPath:
        path: /home/hwanghyun3/toolchain-cdk/bastion
    - name: run-ttyd
      emptyDir: {}
